spring.application.name=backend
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=USER

# The connection string (URL)
spring.datasource.url=jdbc:postgresql://localhost:5432/lunch_vote_db

# Your PostgreSQL credentials
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
