spring.application.name=backend
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.security.user.name=${APP_USER:root}
spring.security.user.password=${APP_PASSWORD:password}
spring.security.user.roles=USER

# The connection string (URL)
#spring.datasource.url=jdbc:postgresql://localhost:5432/lunch_vote_db

# Your PostgreSQL credentials
spring.datasource.username=${DB_DATASOURCE_USER:postgres}
spring.datasource.password=${DB_DATASOURCE_PASSWORD:postgres}

# Hibernate properties
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 1. Stop Hibernate from trying to 'update' or 'validate' the table
spring.jpa.hibernate.ddl-auto=none

# 2. Tell Spring to build the database structure using your SQL scripts
spring.sql.init.mode=always

# 3. This ensures scripts run in the correct order (schema then data)
spring.jpa.defer-datasource-initialization=false

# Email notifications
# application.properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# These tell Spring: "Find a variable named GMAIL_USER. 
# If it's missing, leave this blank."
spring.mail.username=${GMAIL_USER:}
spring.mail.password=${GMAIL_APP_PASS:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Hide your group emails here too
#notification.group-list=${GROUP_EMAILS:}

# Twillio credentials
twilio.sid=${TWILIO_ACCOUNT_SID:AC_placeholder}
twilio.token=${TWILIO_AUTH_TOKEN:token_placeholder}
twilio.from=${TWILIO_PHONE_NUMBER:+15555555555}
my.personal.phone=${MY_PERSONAL_PHONE:+10000000000}
notification.group-list=${GROUP_EMAILS:test@example.com}

app.frontend.url=${FRONTEND_URL:http://localhost:5173}
server.port=${PORT:8080}