spring.application.name=backend
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=USER

# The connection string (URL)
spring.datasource.url=jdbc:postgresql://localhost:5432/lunch_vote_db

# Your PostgreSQL credentials
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Tells Spring to run data.sql
spring.sql.init.mode=always
# Ensures Hibernate creates tables before data.sql tries to insert into them
spring.jpa.defer-datasource-initialization=true

# Email notifications
# application.properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# These tell Spring: "Find a variable named GMAIL_USER. 
# If it's missing, leave this blank."
spring.mail.username=${GMAIL_USER:}
spring.mail.password=${GMAIL_APP_PASS:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Hide your group emails here too
notification.group-list=${GROUP_EMAILS:}


# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=adiemer@gmail.com
# spring.mail.password=rgoyukzsyzxqaefw
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true
